name: Build plugin
on:
  push:
    tags:
      - "*"
env:
  PLUGIN_NAME: logseq-query-builder-plugin
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: build
        run: |
          mkdir ${{ env.PLUGIN_NAME }} # folder for zip
          cp LICENSE README.md icon.png package.json index.html index.js style.css  ${{ env.PLUGIN_NAME }} # move build assets
          zip -r ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip ${{ env.PLUGIN_NAME }} # create zip
      - name: Create Release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: true
          token: ${{ secrets.github_token }}
          files: |
            ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip
